config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :user do
    get 'guest_login' => 'public/sessions#guest_login'
  end

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #ユーザー用ルーティング
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "mypage" => "users#mypage", as: "mypage"
    get "search" => "searches#search"
    patch "users/withdraw" => "users#withdraw", as: "withdraw"
    resources :users, only: [:edit, :show, :update,] do
      member do
        get :follows, :followeds, :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    get "posts/example" => "posts#example", as: "example"
    resources :posts do
      resources :comments, except: [:edit, :update, :index]
    end
    resources :favorites, only: [:create, :destroy]
    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:show, :create, :destroy]
    resources :groups do
      resource :groupusers, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
    end
  end

  #管理者用ルーティング
  namespace :admin do
    root to: "homes#top"
    patch "users/withdraw" => "users#withdraw"
    get "search" => "searches#search"
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:show, :destroy]
    end
    resources :users, only: [:index, :show] do
      member do
        get :follows, :followeds, :favorites
      end
    end
    resources :groups, only: [:index, :show, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image

  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 200 }

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :caption, length: { maximum: 150 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 150 }
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  has_many :comments,  dependent: :destroy
  has_many :favorites, dependent: :destroy

  belongs_to :user

  validates :body, presence: true, length: { maximum: 300 }

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries,  dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  #投稿に関連するアソシエーション
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  #グループ機能に関するアソシエーション
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  #DM機能に関するアソシエーション
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  #フォローに関するアソシエーション
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :follows, through: :active_relationships, source: :followed
  #フォロワーに関するアソシエーション
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followeds, through: :passive_relationships, source: :follow

  validates :name, presence: true
  validates :nickname, presence: true
  validates :caption, length: { maximum: 150 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  def guest?
    email == 'guest@example.com'
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def follows?(user)
    follows.include?(user)
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!
  
  def search
    word = params['word']
    @users = partical_user(word)
    @posts = partical_post(word)
    @groups = partical_group(word)
  end

  private

  def partical_user(word)
    User.where('nickname LIKE ?', "%#{word}%")
  end

  def partical_post(word)
    Post.where('body LIKE ?', "%#{word}%")
  end

  def partical_group(word)
    Group.where('name LIKE ?', "%#{word}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/searches/search.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <ul class="tab-list list-unstyled d-flex">
        <li class="tab tab-active text-center">
          ユーザー
        </li>
        <li class="tab text-center">
          投稿
        </li>
        <li class="tab text-center">
          グループ
        </li>
      </ul>
    </div>
  </div>

  <div class="tabbox-contents">
    <div class="tabbox box-show" data-tag="ユーザー">
      <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-12 text-center">
          <p class="pheader">ユーザー検索結果</p>
        </div>
      </div>
      <% @users.each do |user| %>
        <%= link_to admin_user_path(user), class: "text-dark" do %>
          <table class="table border-top border-bottom table-hover table-inverse">
            <tbody>
              <tr>
                <td class="result-head">
                  <%= image_tag user.get_profile_image(75, 75) %>
                </td>
                <% if user.is_active == true %>
                  <td class="td-body align-middle">
                    <b><%= user.nickname %></b>
                  </td>
                <% else %>
                  <td class="td-body align-middle text-danger">
                    <b><%= user.nickname %></b>
                  </td>
                <% end %>
               <td class="result-foot align-middle"><%= user.caption %></td>
              </tr>
            </tbody>
          </table>
        <% end %>
      <% end %>
    </div>
    <div class="tabbox" data-tag="投稿">
      <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-12 text-center">
          <p class="pheader">投稿検索結果</p>
        </div>
      </div>
      <% @posts.each do |post| %>
        <%= link_to admin_post_path(post), class: "text-dark" do %>
          <table class="table border-top border-bottom table-hover table-inverse">
            <tbody>
              <tr>
                <td class="result-head"><%= image_tag post.user.get_profile_image(50, 50) %> <%= post.user.nickname %></td>
                <td class="td-body align-middle">
                  <b><%= post.body %></b>
                </td>
                <td class="result-foot align-middle"><i class="fa-regular fa-comment"></i> <%= post.comments.count %></td>
              </tr>
            </tbody>
          </table>
        <% end %>
      <% end %>
    </div>
    <div class="tabbox" data-tag="グループ">
      <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-12 text-center">
          <p class="pheader">グループ検索結果</p>
        </div>
      </div>
      <% @groups.each do |group| %>
        <%= link_to admin_group_path(group), class: "text-dark" do %>
          <table class="table border-top border-bottom table-hover table-inverse">
            <tbody>
              <tr>
                <td class="result-head">
                  <%= image_tag group.get_image(75, 75) %>
                </td>
                <td class="td-body align-middle">
                  <b><%= group.name %></b>
                </td>
                <td class="result-foot align-middle">
                  <%= group.caption %>
                </td>
              </tr>
            </tbody>
          </table>
        <% end %>
      <% end %>
    </div>
  </div>
</div>