config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :user do
    get 'guest_login' => 'public/sessions#guest_login'
  end

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #ユーザー用ルーティング
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "mypage" => "users#mypage", as: "mypage"
    get "search" => "searches#search"
    patch "users/withdraw" => "users#withdraw", as: "withdraw"
    resources :users, only: [:edit, :show, :update,] do
      member do
        get :follows, :followeds, :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    get "posts/example" => "posts#example", as: "example"
    resources :posts do
      resources :comments, except: [:edit, :update, :index]
    end
    resources :favorites, only: [:create, :destroy]
    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:show, :create, :destroy]
    resources :groups do
      resource :groupusers, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
    end
  end

  #管理者用ルーティング
  namespace :admin do
    root to: "homes#top"
    patch "users/withdraw" => "users#withdraw"
    get "search" => "searches#search"
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:show, :destroy]
    end
    resources :users, only: [:index, :show] do
      member do
        get :follows, :followeds, :favorites
      end
    end
    resources :groups, only: [:index, :show, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image

  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 200 }

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :caption, length: { maximum: 150 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 150 }
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  has_many :comments,  dependent: :destroy
  has_many :favorites, dependent: :destroy

  belongs_to :user

  validates :body, presence: true, length: { maximum: 300 }

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries,  dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  #投稿に関連するアソシエーション
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  #グループ機能に関するアソシエーション
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  #DM機能に関するアソシエーション
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  #フォローに関するアソシエーション
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :follows, through: :active_relationships, source: :followed
  #フォロワーに関するアソシエーション
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followeds, through: :passive_relationships, source: :follow

  validates :name, presence: true
  validates :nickname, presence: true
  validates :caption, length: { maximum: 150 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  def guest?
    email == 'guest@example.com'
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def follows?(user)
    follows.include?(user)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
    @post = Post.find(params[:id])
    @detail_page = true
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/_post_list.erb
<div class="border-top border-bottom">
  <div class="post-row row">
    <div class="col-md-2 col-4">
      <%= link_to admin_user_path(post.user_id) do %>
        <%= image_tag post.user.get_profile_image(100, 100), class: "image" %>
      <% end %>
    </div>
    <div class="post col-md-4 col-4 text-left">
      <b><%= post.user.nickname %></b>
    </div>
    <div class="col-md-2 offset-md-2 col-3 text-secondary">
      <%= post.created_at.strftime("%-m/%-d %H:%M") %>
    </div>
  </div>

  <% if !defined? @detail_page %>
    <%= link_to admin_post_path(post), class: "text-dark" do %>
      <div class="row align-items-end">
        <div class="post col-md-6 col-12 offset-md-2">
          <div>
              <%= post.body %>
          </div>
        </div>
        <% if post.image.present? %>
        <div class="col-md-6 offset-md-2 col-12">
          <%= image_tag post.get_image(300, 300) %>
        </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="row align-items-end">
      <div class="post col-md-6 offset-md-2 col-12">
        <div>
            <%= post.body %>
        </div>
      </div>
      <% if post.image.present? %>
        <div class="col-md-6 offset-md-2 col-12">
          <%= image_tag post.get_image(300, 300) %>
        </div>
      <% end %>
      <div class="col-md-2 offset-md-2 col-12">
        <%= link_to "削除", admin_post_path(post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

<div class="border-bottom">
  <div class="item-row row d-flex justify-content-evenly align-items-center">
    <div class="col-md-2 offset-md-2 col text-center">
        <i class="fa-regular fa-comment"></i> <%= post.comments.count %>
    </div>
    <div class="col-md-2 col text-center">
      <i class="fa-solid fa-heart text-primary"></i>
      <%= post.favorites.count %> いいね
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container justify-content-center">
  <div class="row mt-3 d-flex justify-content-center">
    <div class="col-md-3 col-12">
      <p class="pheader">投稿一覧</p>
    </div>
  </div>

  <% @posts.each do |post| %>
    <%= render 'post_list', post: post %>
  <% end %>

  <div class="row">
    <div class="col-md-4 offset-md-4 col-12 text-center">
      <div class="pagination">
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 col-12 text-center">
      <p class="pheader">投稿詳細</p>
    </div>
  </div>

  <%= render 'post_list', post: @post %>

  <% @post.comments.each do |comment| %>
    <%= link_to admin_post_comment_path(post_id: @post.id, id: comment.id), class: "text-dark" do %>
      <div class="border-top border-bottom">
        <div class="comment-row row">
          <div class="col-md-2 col-4">
            <%= image_tag comment.user.get_profile_image(75, 75) %>
          </div>
          <div class="col-md-4 col-4 text-left">
            <b><%= comment.user.nickname %></b>
          </div>
          <div class="col-md-2 offset-md-2 col-3 text-secondary">
            <%= comment.created_at.strftime("%-m/%-d %H:%M") %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 offset-md-2 col-12">
            <div>
                <%= comment.comment %>
            </div>
          </div>
          <% if comment.image.present? %>
            <div class="col-md-6 offset-md-2 col-12">
              <%= image_tag comment.get_image(300, 300) %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>