config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :user do
    get 'guest_login' => 'public/sessions#guest_login'
  end

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #ユーザー用ルーティング
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "mypage" => "users#mypage", as: "mypage"
    get "search" => "searches#search"
    patch "users/withdraw" => "users#withdraw", as: "withdraw"
    resources :users, only: [:edit, :show, :update,] do
      member do
        get :follows, :followeds, :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    get "posts/example" => "posts#example", as: "example"
    resources :posts do
      resources :comments, except: [:edit, :update, :index]
    end
    resources :favorites, only: [:create, :destroy]
    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:show, :create, :destroy]
    resources :groups do
      resource :groupusers, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
    end
  end

  #管理者用ルーティング
  namespace :admin do
    root to: "homes#top"
    patch "users/withdraw" => "users#withdraw"
    get "search" => "searches#search"
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:show, :destroy]
    end
    resources :users, only: [:index, :show] do
      member do
        get :follows, :followeds, :favorites
      end
    end
    resources :groups, only: [:index, :show, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image

  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 200 }

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :caption, length: { maximum: 150 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 150 }
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  has_many :comments,  dependent: :destroy
  has_many :favorites, dependent: :destroy

  belongs_to :user

  validates :body, presence: true, length: { maximum: 300 }

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries,  dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  #投稿に関連するアソシエーション
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  #グループ機能に関するアソシエーション
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  #DM機能に関するアソシエーション
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  #フォローに関するアソシエーション
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :follows, through: :active_relationships, source: :followed
  #フォロワーに関するアソシエーション
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followeds, through: :passive_relationships, source: :follow

  validates :name, presence: true
  validates :nickname, presence: true
  validates :caption, length: { maximum: 150 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  def guest?
    email == 'guest@example.com'
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def follows?(user)
    follows.include?(user)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @detail_page = true
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_active: false)
    reset_session
    flash[:notice] = "退会させました"
    redirect_to admin_users_path
  end

  def favorites
    @user = User.find(params[:id])
    favorites_post_ids = Favorite.where(user_id: @user.id).pluck(:post_id)
    @posts = Post.where(id: favorites_post_ids).page(params[:page]).per(5)
  end

  def follows
    user = User.find(params[:id])
    @users = user.follows.page(params[:page]).per(10)
  end

  def followeds
    user = User.find(params[:id])
    @users = user.followeds.page(params[:page]).per(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_list.erb
<% users.each do |user| %>
  <div class="border-top border-bottom">
    <div class="user-row row">
      <div class="col-md-2 col-4">
        <%= link_to admin_user_path(user) do %>
          <%= image_tag user.get_profile_image(100, 100), class: "image" %>
        <% end %>
      </div>
      <div class="user col-md-4 col-4 text-left">
        <% if user.is_active == true %>
          <b><%= user.nickname %></b>
        <% else %>
          <b class="text-danger"><%= user.nickname %></b>
        <% end %>
      </div>
      <div class="col-md-2 offset-md-2 col-3 text-secondary">
        <%= user.name %>
      </div>
    </div>


    <div class="row align-items-end">
      <div class="user col-md-6 offset-md-2 col-12">
        <div>
          <%= user.caption %>
        </div>
      </div>
  </div>
<% end %>

app/views/admin/users/favorites.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 col-12 text-center">
      <p class="pheader">いいね一覧</p>
    </div>
  </div>

  <% @posts.each do |post| %>
    <%= render 'admin/posts/post_list', post: post %>
  <% end %>

  <div class="row">
    <div class="col-4 offset-4 text-center">
      <div class="pagination">
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/followeds.erb
<div class="container justify-content-center">
  <div class="row mt-3 d-flex justify-content-center">
    <div class="col-md-5 col-12">
      <p class="pheader">フォロワー一覧</p>
    </div>
  </div>

  <%= render 'list', users: @users %>

  <div class="row">
    <div class="col-4 offset-4 text-center">
      <div class="pagination">
        <%= paginate @users %>
      </div>
    </div>
  </div>
  
</div>

app/views/admin/users/follows.erb
<div class="container justify-content-center">
  <div class="row mt-3 d-flex justify-content-center">
    <div class="col-md-5 col-12">
      <p class="pheader">フォロー一覧</p>
    </div>
  </div>

  <%= render 'list', users: @users %>

  <div class="row">
    <div class="col-4 offset-4 text-center">
      <div class="pagination">
        <%= paginate @users %>
      </div>
    </div>
  </div>

</div>

app/views/admin/users/index.html.erb
<div class="container justify-content-center">
  <div class="row mt-3 d-flex justify-content-center">
    <div class="col-md-5 col-12">
      <p class="pheader">ユーザー一覧</p>
    </div>
  </div>

  <% @users.each do |user| %>
    <div class="border-top border-bottom">
      <div class="user-row row">
        <div class="col-md-2 col-4">
          <%= link_to admin_user_path(user) do %>
            <%= image_tag user.get_profile_image(100, 100), class: "image" %>
          <% end %>
        </div>
        <div class="user col-md-4 col-4 text-left">
          <% if user.is_active == true %>
            <b><%= user.nickname %></b>
          <% else %>
            <b class="text-danger"><%= user.nickname %></b>
          <% end %>
        </div>
        <div class="col-md-2 offset-md-2 col-3 text-secondary">
          <%= user.name %>
        </div>
      </div>


      <div class="row align-items-end">
        <div class="user col-md-6 offset-md-2 col-12">
          <div>
            <%= user.caption %>
          </div>
        </div>
        <% if defined? @detail_page %>
          <div class="col-md-2 offset-md-2 col-12">
            <%= link_to "削除", admin_post_path(post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
          </div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 col-12 text-center">
      <p class="pheader">ユーザー詳細</p>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-md-5 col-12">
      <div class="d-flex justify-content-center">
        <%= image_tag @user.get_profile_image(200, 200) %>
      </div>

      <table class="d-flex justify-content-center">
        <tr>
          <td class="user-table"><b>名前：</b></td>
          <td class="user"><b><%= @user.name %></td>
        </tr>
        <tr>
          <td class="user-table"><b>ニックネーム：</b></td>
          <td class="user"><b><%= @user.nickname %></b></td>
        </tr>
        <tr>
          <td class="user-table"><b>紹介文：</b></td>
          <td class="user"><%= @user.caption %></td>
        </tr>
        <tr>
          <td class="user-table"><b>フォロー：</b></td>
          <td class="user"><%= link_to @user.follows.count, follows_admin_user_path(@user), class: "text-dark" %></td>
        </tr>
        <tr>
          <td class="user-table"><b>フォロワー：</b></td>
          <td class="user"><%= link_to @user.followeds.count, followeds_admin_user_path(@user), class: "text-dark" %></td>
        </tr>
        <tr>
          <td colspan="2"><%= link_to "いいね一覧", favorites_admin_user_path(@user), class: "btn btn-light d-flex justify-content-center border rounded" %></td>
        </tr>
        <tr>
          <td colspan="2">
            <% if @user.is_active == false %>
              <div class="explain mt-2 text-center text-danger">
                <b><%= @user.nickname %>さんは退会済です</b>
              </div>
            <% elsif %>
              <div class="explain mt-2 text-center">
                <%= link_to "退会させる", admin_users_withdraw_path(id: @user.id), method: :patch, class: "btn btn-danger", data: { confirm: "本当に退会しますか？" } %>
              </div>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>