config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :user do
    get 'guest_login' => 'public/sessions#guest_login'
  end

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #ユーザー用ルーティング
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "mypage" => "users#mypage", as: "mypage"
    get "search" => "searches#search"
    patch "users/withdraw" => "users#withdraw", as: "withdraw"
    resources :users, only: [:edit, :show, :update,] do
      member do
        get :follows, :followeds, :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    get "posts/example" => "posts#example", as: "example"
    resources :posts do
      resources :comments, except: [:edit, :update, :index]
    end
    resources :favorites, only: [:create, :destroy]
    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:show, :create, :destroy]
    resources :groups do
      resource :groupusers, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
    end
  end

  #管理者用ルーティング
  namespace :admin do
    root to: "homes#top"
    patch "users/withdraw" => "users#withdraw"
    get "search" => "searches#search"
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:show, :destroy]
    end
    resources :users, only: [:index, :show] do
      member do
        get :follows, :followeds, :favorites
      end
    end
    resources :groups, only: [:index, :show, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image

  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 200 }

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :caption, length: { maximum: 150 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 150 }
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  has_many :comments,  dependent: :destroy
  has_many :favorites, dependent: :destroy

  belongs_to :user

  validates :body, presence: true, length: { maximum: 300 }

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries,  dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  #投稿に関連するアソシエーション
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  #グループ機能に関するアソシエーション
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  #DM機能に関するアソシエーション
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  #フォローに関するアソシエーション
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :follows, through: :active_relationships, source: :followed
  #フォロワーに関するアソシエーション
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followeds, through: :passive_relationships, source: :follow

  validates :name, presence: true
  validates :nickname, presence: true
  validates :caption, length: { maximum: 150 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  def guest?
    email == 'guest@example.com'
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def follows?(user)
    follows.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_search.erb
<% if user_signed_in? %>
  <div class="search-form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.button :type => "submit" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
  </div>
<% elsif admin_signed_in? %>
  <div class="search-form">
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.button :type => "submit" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamersConnection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/73eb502509.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header class="shadow-sm"  style="background-color: rgba(160, 32, 255, 1.0)">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <% if user_signed_in? %>
            <%= link_to mypage_path, class: "text-white" do %>
              <i class="fa-solid fa-earth-asia"></i>
            <% end %>
          <% elsif admin_signed_in? %>
            <%= link_to admin_root_path, class: "text-white" do %>
              <i class="fa-solid fa-earth-asia"></i>
            <% end %>
          <% else %>
            <%= link_to root_path, class: "text-white" do %>
              <i class="fa-solid fa-earth-asia"></i>
            <% end %>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'About', about_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "グループ一覧", groups_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿一覧', posts_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', mypage_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to '新規投稿', new_post_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'メッセージ', rooms_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
            </li>
                
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿一覧', admin_posts_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'グループ一覧', admin_groups_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-white' %>
            </li>



            <% else %>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-white' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="col d-flex justify-content-end">
          <%= render 'layouts/search' %>
        </div>
      </div>
    </header>

    <main>
      <% flash.each do |message_type, message| %>
        <div class="flash_message <%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>